server:
  port: 8081

spring:
  application:
    name: fin


  mongodb:
    uri: mongodb://localhost:27017/finpulse

logging:
  level:
    root: INFO
    springframework.security: DEBUG

jwt:
  secret: okthisismysecretiwilluseeverytime14    //use a secure secret in production
  expiration: 3600000